llm:
  # openai or anthropic
  service: "openai"
  # OpenAI: gpt-3.5-turbo, gpt-4, gpt-3.5-turbo-16k, gpt-4-32k; Anthropic: claude-instant-1 or claude-2
  model: "gpt-3.5-turbo"
  ## OpenAI-specific settings
  # Only used for Azure OpenAI API
  azure_openai_endpoint:
  # Use only with an alternate OpenAI-compatible API endpoint
  openai_endpoint:
  openai_org_id:
nlp:
  server_url: "http://localhost:5557"
memory:
  message_window: 12
extractors:
  documents:
    embeddings:
      enabled: true
      dimensions: 384
      service: "local"
#      dimensions: 1536
#      service: "openai"
  messages:
    summarizer:
      enabled: true
    entities:
      enabled: true
    intent:
      enabled: false
    embeddings:
      enabled: true
      dimensions: 384
      service: "local"
#      dimensions: 1536
#      service: "openai"
store:
  type: "postgres"
  postgres:
    dsn: "postgres://postgres:postgres@localhost:5432/?sslmode=disable"
server:
  port: 8000
auth:
  # Set to true to enable authentication
  required: false
  # Do not use this secret in production. The ZEP_AUTH_SECRET environment variable should be
  # set to a cryptographically secure secret. See the Zep docs for details.
  secret: "do-not-use-this-secret-in-production"
data:
  #  PurgeEvery is the period between hard deletes, in minutes.
  #  If set to 0 or undefined, hard deletes will not be performed.
  purge_every: 60
log:
  level: "info"
