# version: "3"

# services:
#   frontend:
#     env_file:
#       - ./frontend/.env.dev
#     build:
#       context: frontend
#       dockerfile: Dockerfile
#     container_name: web
#     restart: always
#     ports:
#       - 4000:4000

version: "3.8"

networks:
  proxy:
    external: true

services:
  frontend-dev:
    env_file:
      - ./frontend/.env.dev
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    container_name: expergpt-frontend-dev
    restart: always
    ports:
      - 4001:4001
    networks:
      - proxy